### ISSUE TITLE
Pip2 Fails to install the latest api spec version

### ISSUE THREAD

**Issue by patthiel** [linode/linode-cli#130]
When using pip2 to install the linode cli, it installs the correct version, but seems to install the wrong Spec version (4.0.8, instead of the latest 4.1.0). 

This issue has been documented by customers via https://www.linode.com/community/questions/18361/linode-cli-version-mismatch and reproduced. 

I have some theories why this might be happening, and will follow up in this ticket. However, for now, if you encounter this issue, installing the linode cli with `pip3` will fix the issue.

**Comment by gpfjeff** [comment]
I'm the OP for the community post in question, and I can confirm that the problem occurs with pip3 as well as pip2.
It seems rather consistent that every time a new version gets pushed out, there's an API spec mismatch:
1. New version gets released. Existing version starts printing out "The API responded with version x.x.x, which is newer than the CLI's version of y.y.y" warnings.
2. I dutifully attempt a "pip3 install --upgrade linode-cli".
3. Install says I already have the latest version.
4. I uninstall and reinstall. Get the same version.
5. I complain on the Linode community forum.
6. Sometime later, another new version gets pushed out. This time the upgrade works.
I'm not sure if you guys use any sort of automated build, but something isn't getting updated when new versions go out.

**Comment by TrueGit** [comment]
It's happening to me with both pip2 and pip3.  

1.  "linode-cli linodes list" performs the expected list operation but first prompts:

```
The API responded with version 4.5.0, which is newer than the CLI's version 
of 4.4.0.  Please update the CLI to get access to the newest features.  You 
can update with a simple 'pip install --upgrade linode-cli'
```

2.  I've tried "pip2 install --upgrade linode-cli" and "pip3 install --upgrade linode-cli" a few times.  Neither reports an error, but neither seems to be upgrading the linode-cli version.

"linode-cli --version" continues to report: 
```
linode-cli 2.8.1
Built off spec version 4.4.0
```

"linode-cli linodes list" continues to display the "please update the CLI" prompt I quoted above.

I'm on Mac OS 10.14.6, with pip2 version 19.0.3 and pip3 version 19.1.1.

**Comment by gpfjeff** [comment]
According to my pip3--and the Releases page here on GitHub--2.8.1 is still the latest version.

I have a theory. I think the Linode guys either push out the server-side API update first, or they push both the API endpoint and linode-cli  updates at the same time and the CLI gets delayed due to processing in the pip repository. Either way, there is a delay between when server endpoint gets updated and when the pip repository gets updated. During this window, the server endpoint is a version ahead of what's available for the CLI. It makes sense, since the server endpoint is under Linode's control, while the pip repos are not. They're at the mercy of whatever process, manual or automated, approves the change and makes it available.

Personally, I think the warning is a bit unforgiving, and it would be nice if things could be better timed. I have a job set on an hourly cron, so when it starts doing this, it gets **really** annoying. (I pipe STDOUT to /dev/null so if everything works, I don't get an email. But STDERR still gets output, so...) Fortunately, it *is* just a warning, so you can use --suppress-warnings if you're doing something non-interactive like me. In my experience, the new version is visible in the pip repos within 24 hours.

**Comment by TrueGit** [comment]
That's a good theory @gpfjeff, and thank you for the pointers.  I'll be curious to try upgrading my linode-cli again in a day or two.

I don't know Python, but it looks to me like the "Please update the CLI" warning is generated in the "linodecli/cli.py" file, within the "do_request" method of class "CLI":

https://github.com/linode/linode-cli/blob/38b9c60a2749148f80d95f08550050a5af632ad1/linodecli/cli.py#L396-L403

If your theory is correct, and if there is no harm in continuing to use the CLI with a suddenly penultimate API, perhaps it would be a good idea for Linode to append a bit more information to the warning?  Perhaps something more or less like this:

```
Upon an API update, it might take a few days for the CLI to be 
updated to use the new API version.  In the interim, 
'pip install --upgrade linode-cli' will not update the CLI,
but it still will be safe to use the CLI.  You can use the 
'--suppress-warnings' option to suppress this message.
```

**Comment by gpfjeff** [comment]
I don't consider myself a "power user" of the CLI by any means. I use it to automate one or two routine tasks that I do frequently, and the CLI is currently the most convenient (and only) way to automate them. So I'm not sure my suggestions would be the most helpful. I'm just the guy with the loud mouth who started fussing about it first. :)

I don't think there's anything necessarily wrong with the warning itself. I actually think it's rather helpful; I *want* to know when there's a new version, because I want to make sure I keep all my tools up to date. I may not be using every tool on this Swiss army knife, but I want to know the one or two tools I use all the time are still going to work.

So it sounds like PyPI is the real bottleneck, which kind of stinks, but is understandable. Since that's the case, my personal recommendation would be to leave the warning as is, but delay the production deployment of the server-side endpoint until you can confirm that the PyPI repo has been updated. Of course, I say that without knowing how easy that is to do (again, not a Python guy), but I'm guessing you guys do your development and testing in one environment before deploying to production. I'm also guessing you could throw together a script to monitor the PyPI repo to see what version of the CLI is publicly available. You could have the script notify you of the new version release, and potentially automate the endpoint rollout as well. (One caveat to this idea is that it potentially introduces the *opposite* problem: having the CLI version in PyPI ahead of the endpoint version. I have no idea how backward compatible the CLI is, so I realize that could break things just as badly.)

If that won't work, I would suggest Options 1 or 2 you list above. Like I said, I don't think removing the warning altogether is a good idea, but I think the caveats for those options are acceptable, with the understanding that the user realizes what they mean.

Personally, the --suppress-warnings flag is working to meet my current needs. As I mentioned in the original Community Questions post (linked up top), I monitor the release RSS feed here on GitHub, so I know when the new release comes out. The --suppress-warnings flag mutes the warning so my inbox doesn't get flooded, and the RSS feed tells me when to update. This works well enough for me, but I also realize it may not be best for others.

**Comment by TrueGit** [comment]
I'm not a CLI "power user", but here are my two cents in case they're helpful.  Please disregard if they're not.

Like @gpfjeff, I find the warning helpful in that it informs me the API has been updated beyond my CLI version.  I too would like to keep my CLI up to date, and I'm also grateful for the reminder of the PIP command to do that.  The notice may also prompt me to read the API change log, if I'm so inclined, in case there is a new feature I might like to use or an issue I should know about.  Even if the CLI has not been updated to access a new API feature yet, if the feature is significant to me, perhaps I would access it with CURL pending the CLI update.

I see two drawbacks with the current warning:

- First, the "Please update the CLI" part implies there is an updated CLI available, which at least for some initial window of time is not correct.  Within that window, it therefore surprises and alarms the uninitiated user when the PIP command does not result in an update.  "Did I type it correctly?  Is something else wrong?"  Which leads to Web searching, browsing Github issues, etc.

- Second, the "Please update" language is sufficiently imperative that the user may worry, as I did, whether it's still safe to be using the suddenly out-of-date CLI.

I think it would be easiest and an improvement to leave the warning in place but edit its wording slightly to remedy the above two drawbacks.

Less easy, but best, I think, as @gpfjeff suggests, would be to coordinate the pushing of CLI and API updates so there is no significant period of time that they are out of sync.

If that's not possible, perhaps it would be somewhat easier to change the content of the warning message so it accurately informs what the latest CLI version available is.  For example:

   - If the user has the latest CLI version, but it is behind the latest API version, the warning would alert that a later API version is available, and that a conforming CLI update will be available soon.  There would be no prompt to run an ineffectual CLI update command, however.  

   - If the user's CLI version is behind the latest CLI version, the user would be prompted to update to the latest CLI version available, even if the latest CLI doesn't yet match the latest API.

**Comment by Dorthu** [comment]
Thanks for the feedback!  It sounds like the warning itself is helpful and desirable as long as there is actually a new CLI version ready to update to in all cases.  It also looks like PyPI has an API that can retrieve current package versions.. I'm going to experiment with fetching the most recent version from PyPI and only presenting the warning if there is in fact a new version to upgrade to.  If that doesn't add too much overhead I'll put up a PR for it.

**Comment by Dorthu** [comment]
I opened #137 to address this issue.  Let me know what you think.

**Comment by patthiel** [comment]
@Dorthu  I like the proposed solution. It addresses the possibility that pypi might not display our new version right away and more reliably message to users when a new version is actually available.

A while back, i added a check that compared the CLI built-off spec version against the X-Api-spec-version returned by the api, and made it _Not_ display the warning if the versions were a patch version different. Prior to that change, the warning was displayed roughly once every two to three weeks with insignificant, non-CLI impacting spec changes prompting users to upgrade.

Example:
```
X-Spec-Version (returned by api call): 4.5.1
Linode-CLI built-off API Spec: 4.5.0
```

Currently, the above would not display the warning to CLI users, since we typically don't ship new CLI releases for patch version changes to the spec (too much overhead for fairly insignificant changes made in patch versions).

Long winded way of saying, I don't the above check is necessary with @Dorthu's proposed solution. We'll be checking the current CLI version installed against what API returns and comparing that against what pypi has. If a patch version is released, the CLI will do the check and pypi won't have anything new, thus the warning will not display.

@TrueGit @gpfjeff thank you for your patience with this, and apologies that this has been a recurring issue.  We're really happy this tool has been integrated into your workflows, and please do let us know if you have feedback on @Dorthu's proposed solution or more generally for how we can make this tool even better!

**Comment by TrueGit** [comment]
I think your proposed solution in #137 looks great, @Dorthu!  Thank you to you and @patthiel, and to Linode.  I've only been using the linode-cli off and on for several weeks, but I've found it very useful and efficiency-enhancing.  I'm thrilled to have it in my toolkit, and I hope to use it for more and more things compared to the browser interface as I become more familiar with it.

**Comment by gpfjeff** [comment]
Sounds like a reasonable approach to me. I'm not opposed to the client-side check to PyPI, although like @Dorthu I can foresee _someone_ out there being a little antsy about it. (Overly paranoid folks who obsessively watch their traffic with Wireshark, maybe? It's nothing compared to everything Microsoft that phones home to the mothership...)

Thanks for looking into this, guys. Been a Linode customer for eight years now, and while I've had the occasional rough patch here and there, I've stuck with you longer than I've been with any other host. Keep up the great work.
