### ISSUE TITLE
Improve json output flags

### ISSUE THREAD

**Issue by Dorthu** [linode/linode-cli#153]
Currently, if you call `linode-cli linodes list --pretty`, the `--pretty` is ignored, as it currently only works with `--json`.

Likewise, by default, `--json` only shows the attributes that would normally be displayed in the table, instead of everything (`--all` is required to show full JSON responses).

This issue is to propose that `--pretty` should imply `--json` (so that both aren't needed for pretty JSON output), and `--json` always implies `--all` (unless `--format` is provided, in which case only those fields are displayed).

**Comment by Dorthu** [comment]
CC @caker who suggested the first half of this.

**Comment by stvnjacobs** [comment]
- `--pretty` should imply `--json`
  - I am indifferent about this one. I think the use of `jq` is ubiquitous enough that most are using it when working with json on the command line. If it improves the lives of others who don't, :+1:.
- `--json` always implies `--all` (unless `--format` is provided, ...)
  - Yes please. I think this is a good quality of life improvement. As noted, I prefer to use `jq` for tasks involving json, which includes using it to filter json fields rather than learning each tools API. I think this makes sense for most instances of needing json.
