### ISSUE TITLE
Delete Kubernetes Node Pools

### ISSUE THREAD

**Issue by sentabi** [linode/linode-cli#185]
I'm trying to delete K8s Node Pools using cli, example
`linode-cli linodes delete id`
checking using `linode-cli linodes list` it;s gone from the list. 

but after few minutes somehow the the pools back

**Comment by LBGarber** [comment]
Thanks for the report!

The deletion of node pools should be handled through the appropriate Kubernetes API or engine rather than by directly deleting instances. Many of these engines will automatically reprovision nodes if they're found to be unhealthy or missing.

For example, users can delete LKE node pools using the following command:

```
linode-cli lke pool-delete {cluster_id} {pool_id}
```
