### ISSUE TITLE
Feature Request: manage account IP white lists

### ISSUE THREAD

**Issue by lwm** [linode/linode-cli#45]
Hi there, we're a company using Linode and working in many different locations and therefore have a lot of white listed IPs on our account. Some of those do not have a note and we are thinking about implementing a process whereby non-noted white listed IPs for the account get wiped each day.

As far as I can see, it is not possible to access the IP white list from the existing version of this tool.

In fact, after some looking, it is not available on the API either?

> https://developers.linode.com/api/v4

Where could I go about getting this feature request seen to if not here?

Thanks.

**Comment by Dorthu** [comment]
This is a great place for a feature request!  Since it's not in the API I'll have to forward the request on internally, but I'll keep you updated here.

**Comment by lwm** [comment]
Thanks a lot @Dorthu! Happy to help out on some implementation if needed!

**Comment by Dorthu** [comment]
It looks like we're phasing out IP whitelisting in favor of Two Factor Authentication - because of this, it was left out of the new API (and the CLI as a result).  Does enabling Two Factor Authentication to secure your accounts fit your workflow?  Would additional tooling around TFA make it easier to switch?

**Comment by lwm** [comment]
Ah right, 2FA will work then! I'll let the rest of the team know. Thanks for finding out :+1:
