### ISSUE TITLE
Relationship between linode_api4-python

### ISSUE THREAD

**Issue by lwm** [linode/linode-cli#46]
Hi there. Thanks for this project.

I'm wondering about what is the relationship between https://github.com/linode/linode_api4-python and this project since I can't see this project pulls in the api4-python project. This project seems to roll all of it's own logic for requesting the API, is that correct? I know the api4-python projec is beta right now however ...

I'm asking since I am in the process of building automation for Linode with Ansible (see https://github.com/ansible/ansible/pull/45406) and want to pick where I should point my upstream contributions. I assume https://github.com/linode/linode_api4-python for that?

BTW, this library is pretty interesting, in that, I can't really find any logic which is actually doing anything here. It's all just a wrapper for forwarding OpenAPI client commands? Is this the case? Pretty cool ...

**Comment by Dorthu** [comment]
Thanks for your interest!  You are correct - this project generates its actions from the OpenAPI spec, and therefore has no connection to the python library (they just happen to both be in python because that's what I've been working in lately).  The python library is probably the right pick for ansible, as this project is intended to be used through the command line.

I'm responding to your issue on linode_api4-python too, so I'll see you over there!

**Comment by lwm** [comment]
Thanks @Dorthu! That all makes sense then. Solid work over here :smile_cat:
