### ISSUE TITLE
Running apt upgrade on Ubuntu 20.04 Bionic results in unexpected and disruptive behaviour 

### ISSUE THREAD

**Issue by programingnotes** [linode/linode-cli#64]
Issue: 
 - when using ansible to automate system configuration, running `apt update` results in changed grub settings 

```
A new version (/tmp/grub.m5c6gNlnhk) of configuration file /etc/default/grub is available, but the version   installed currently has been locally modified.   
```

Now there isn't a way to select to keep the local version currently installed with ansible (at least that I know of). How do we handle this?

Also, how are we supposed to handle this when doing updates unattended?

[As](https://www.linode.com/community/questions/17018/grub-updated-its-configuration-and-now-there-are-issues) [you](https://www.linode.com/community/questions/17015/grub-default-settings) [can](https://www.linode.com/community/questions/17042/cant-install-kernel-because-it-asks-for-grub-cant-install-grub-because-it-asks-f) see a number of people do not know how to resolve/handle this problem. Your feedback is greatly appreciated. 

Thanks.

**Comment by Dorthu** [comment]
[Linode's community site](https://www.linode.com/community/questions/) would also be a great place to get help with an issue like this, both from our support staff and the wider community who may've already encountered this issue themselves.  I'd encourage you to ask this question there, and I plan to close this issue shortly since it's not related to the CLI.

**Comment by programingnotes** [comment]
okay, thanks for the suggestions on best place to ask; will follow up there.
